export default [
  {
    id: 1,
    name: 'John Doe',
    designation: 'Software Engineer',
    department: 'IT',
    salary: 60000,
    gender: 'male',
    email: 'john.doe@example.com',
  },
  {
    id: 2,
    name: 'Jane Smith',
    designation: 'Project Manager',
    department: 'Operations',
    salary: 80000,
    gender: 'female',
    email: 'jane.smith@example.com',
  },
  {
    id: 3,
    name: 'Michael Johnson',
    designation: 'UI/UX Designer',
    department: 'Design',
    salary: 55000,
    gender: 'male',
    email: 'michael.johnson@example.com',
  },
  {
    id: 4,
    name: 'Emily Davis',
    designation: 'HR Executive',
    department: 'Human Resources',
    salary: 45000,
    gender: 'female',
    email: 'emily.davis@example.com',
  },
  {
    id: 5,
    name: 'David Wilson',
    designation: 'Data Analyst',
    department: 'Analytics',
    salary: 65000,
    gender: 'male',
    email: 'david.wilson@example.com',
  },
];
